app/todo/models.py
from app import db

class Todo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    description = db.Column(db.String(200))
    complete = db.Column(db.Boolean)

app/todo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length


class ToDoForm(FlaskForm):
    title = StringField('Todo Title', validators=[DataRequired("This field is required"), Length(min=1, max=100)])
    description = StringField('', validators=[DataRequired("This field is required"), Length(min=1 , max=200)])
    submit = SubmitField("Add new task")

app/todo/__init__.py
from flask import Blueprint

todo = Blueprint('todo', __name__, template_folder='templates')

app/todo/views.py
from flask import render_template, redirect, url_for, flash
from flask_login import login_required

from app import db
from app.todo import todo
from app.todo.forms import ToDoForm
from app.todo.models import Todo


@todo.route('/todo_list')
@login_required
def todo_list():
    todolist = db.session.query(Todo).all()
    return render_template("todo.html", todo_list=todolist, active="ToDo", title="ToDo")

@todo.route('/view_todo/<int:todo_id>')
def view_todo(todo_id):
    todo = Todo.query.get(todo_id)
    return render_template("view_todo.html", todo=todo)

@todo.route("/add_todo", methods=["POST"])
def add_todo():
    todo_form = ToDoForm()
    if todo_form.validate_on_submit():
        title = todo_form.title.data
        description = todo_form.description.data
        new_todo = Todo(title=title, description=description, complete=False)
        db.session.add(new_todo)
        db.session.commit()
        flash("Todo task has been successfully added", category='flash-success')
        return redirect(url_for("todo.todo_list"))
    flash("Error adding todo task", category='flash-error')
    return redirect(url_for("todo.todo_list"))

@todo.route("/update_todo/<int:todo_id>")
@login_required
def update_todo(todo_id):
    todo = Todo.query.get(todo_id)
    todo.complete = not todo.complete
    db.session.commit()
    return redirect(url_for("todo.view_todo", todo_id=todo_id))

@todo.route("/delete_todo/<int:todo_id>")
@login_required
def delete_todo(todo_id):
    todo = Todo.query.get(todo_id)
    db.session.delete(todo)
    db.session.commit()
    flash("Todo task has been successfully deleted", category='flash-success')
    return redirect(url_for("todo.todo_list"))

@todo.route("/create_todo")
@login_required
def create_todo():
    todo_form = ToDoForm()
    return render_template("create_todo.html", todo_form=todo_form)

app/todo/templates/create_todo.html
{% extends 'base.html' %}

{% macro render_field(field, placeholder='') %}
    {% if field.id == 'title' %}
        {{ field(placeholder="Enter the task's title: ") }}<br><br>
    {% elif field.id == 'description' %}
        {{ field(placeholder="Enter the task's description: ") }}<br><br>
    {% else %}
        {{ field(placeholder=placeholder, class='underline') }}<br><br>
    {% endif %}
    {% if field.errors %}
        <ul class="errors">
            {% for error in field.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endmacro %}


{% block content %}
    <section>
        <div class="pageSection">
            <h2>Create todo</h2>
            <form action="/add_todo" method="POST" class="todoForm" novalidate>
                {{ todo_form.csrf_token }}
                {{ render_field(todo_form.title) }}
                {{ render_field(todo_form.description) }}
                {{ render_field(todo_form.submit) }}
            </form>
        </div>
  </section>
{% endblock %}

app/todo/templates/todo.html
{% extends 'base.html' %}

{% block content %}
    <section>
        <div class="pageSection">
            <h2>List of tasks: </h2>
            <br>
            {% if todo_list|length == 0 %}
                <h3>There are no todos yet</h3>
            {% else %}
                <ul>
                    {% for todo in todo_list %}
                        <li>
                            <h3><a class="postAnchor" href="{{ url_for('todo.view_todo', todo_id=todo.id) }}">{{ todo.title }}</a></h3>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
            <br><br>
            <a class="underline" href="{{ url_for('todo.create_todo') }}">Create new todo</a>
        </div>
    </section>
{% endblock %}

app/todo/templates/view_todo.html
{% extends 'base.html' %}

{% block content %}
    <section>
        <div class="pageSection">
            <h1>Name of the task: <span class="underline">{{ todo.title }}</span></h1>
            <h2>Task description: <span class="underline">{{ todo.description }}</span></h2>
            <h3>Status:
                {% if todo.complete %}
                    <span class="todoMessageCompleted"><strong>Completed</strong></span>
                {% else %}
                    <span class="todoMessageIncomplete"><strong>In progress</strong></span>
                {% endif %}
            </h3>
            <br><br>

            <h3>Actions: </h3>
            {% if todo.complete %}
            <a class="underline" href="/update_todo/{{ todo.id }}" role="button">Mark/Unmark as complete</a>
            <br>
            {% else %}
            <a class="underline" href="/update_todo/{{ todo.id }}" role="button">Mark/Unmark as complete</a>
            <br>
            {% endif %}
            <a class="underline" href="/delete_todo/{{ todo.id }}" role="button">Delete</a>
            <br>
            <a class="underline" href="/todo_list" role="button">Back to the main todo page</a>
            <br>
        </div>
  </section>
{% endblock %}